#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TS="$(date +%Y%m%d%H%M%S)"

OUT_DIR="$HOME/.config/opencode"
OUT_FILE="$OUT_DIR/AGENTS.md"

mkdir -p "$OUT_DIR"

# Backup existing AGENTS.md (keep debugging easy).
if [[ -e "$OUT_FILE" || -L "$OUT_FILE" ]]; then
  mv "$OUT_FILE" "${OUT_FILE}.bak.${TS}"
fi

{
  echo "# OpenCode Global Rules (managed by agent-pack)"
  echo
  echo "This file is generated by agent-pack."
  echo "Source of truth: $ROOT"
  echo
  echo "## Global Charter"
  echo "- $ROOT/claude/CLAUDE.md"
  echo
  echo "## Rules (modules)"

  # Core-only: keep always-loaded rules small.
  # Domain-specific guidance should live in skills (loaded on-demand).
  RULE_FILES=(
    "$ROOT/claude/rules/00-core.md"
    "$ROOT/claude/rules/05-session-context.md"
    "$ROOT/claude/rules/06-automation-warn-hooks.md"
    "$ROOT/claude/rules/07-manual-skill-loading.md"
  )

  if (( ${#RULE_FILES[@]} == 0 )); then
    echo "- (none found at $ROOT/claude/rules/*.md)"
  else
    for f in "${RULE_FILES[@]}"; do
      echo "- $f"
    done
  fi

  echo
  echo "## Skills"
  echo "- $ROOT/claude/skills/"
} > "$OUT_FILE"

echo "wrote: $OUT_FILE"
